apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appBlue.name }}-php-v2
  namespace: {{ .Values.appBlue.namespace }}
  labels:
    app: {{ .Values.appBlue.name }}-php
    version: v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.appBlue.name }}-php
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.appBlue.name }}-php
        version: v2
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "9253"
         prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: {{ .Values.appBlue.imageGreen }}
        name: php
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        
        volumeMounts:
        - name: {{ .Values.appBlue.fileserver }}
          mountPath: /usr/local/apache2/htdocs/
      - name: php-fpm-exporter
        image: "quay.io/sysdig/php-fpm-exporter:v2.3.0"
        ports:
        - containerPort: 9253
        env:
        - name: PHP_FPM_WEB_LISTEN_ADDRESS
          value: :9253
        - name: PHP_FPM_WEB_TELEMETRY_PATH
          value: /metrics
        - name: PHP_FPM_SCRAPE_URI
          value: tcp://127.0.0.1:9000/status
        - name: PHP_FPM_FIX_PROCESS_COUNT
          value: "false"
        - name: PHP_FPM_LOG_LEVEL
          value: info
      volumes:
      - name: {{ .Values.appBlue.fileserver }}
        persistentVolumeClaim:
          claimName: {{ .Values.appBlue.fileserver }}
      - configMap:
            defaultMode: 420
            name: {{ .Values.appBlue.configMap.name }}
        name: {{ .Values.appBlue.configMap.name }}
