apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appGreen.bdService }}
  namespace: {{ .Values.appGreen.namespace }}
spec:
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
  - name: mysql-exporter
    protocol: TCP
    port: 9104
  selector:
    app: {{ .Values.appGreen.name }}-mysql
  clusterIP: None