{{ if.Values.appGreen.lb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appGreen.name }}-loadbalancer
  namespace: {{ .Values.appGreen.namespace }}
spec:
  selector:
    app: {{ .Values.appGreen.name }}-php
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.appGreen.serviceType }}
{{ end }}