apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appGreen.ingress.service.name }}
  namespace: {{ .Values.appGreen.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appGreen.name }}-php

  