apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appGreen.pvClaim }}
  namespace: {{ .Values.appGreen.namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo