apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appBlue.bdService }}
  namespace: {{ .Values.appBlue.namespace }}
spec:
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
  - name: mysql-exporter
    protocol: TCP
    port: 9104
  selector:
    app: {{ .Values.appBlue.name }}-mysql
  clusterIP: None