{{ if.Values.appBlue.lb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appBlue.name }}-loadbalancer
  namespace: {{ .Values.appBlue.namespace }}
spec:
  selector:
    app: {{ .Values.appBlue.name }}-php
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.appBlue.serviceType }}
  {{ end }}