apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myweb-blue-vs
  namespace: php
  labels:
    kiali_wizard: request_routing
spec:
  http:
    - route:
        - destination:
            host: {{ .Values.appBlue.ingress.service.name }}
            subset: v1
          weight: 100
        - destination:
            host: {{ .Values.appBlue.ingress.service.name }}
            subset: v2
          weight: 0
  hosts:
    - '*'
  gateways:
    - php/php-service-blue-gateway

