apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appGreen.name }}-php
  namespace: {{ .Values.appGreen.namespace }}
  labels:
    app: {{ .Values.appGreen.name }}-php
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.appGreen.name }}-php
  template:
    metadata:
      labels:
        app: {{ .Values.appGreen.name }}-php
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9253"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: {{ .Values.appGreen.image }}
        name: php
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        
        volumeMounts:
        - name: {{ .Values.appGreen.fileserver }}
          mountPath: /usr/local/apache2/htdocs/
      - name: php-fpm-exporter
        image: "quay.io/sysdig/php-fpm-exporter:v2.3.0"
        ports:
        - containerPort: 9253
        env:
        - name: PHP_FPM_WEB_LISTEN_ADDRESS
          value: :9253
        - name: PHP_FPM_WEB_TELEMETRY_PATH
          value: /metrics
        - name: PHP_FPM_SCRAPE_URI
          value: tcp://127.0.0.1:9000/status
        - name: PHP_FPM_FIX_PROCESS_COUNT
          value: "false"
        - name: PHP_FPM_LOG_LEVEL
          value: info
      volumes:
      - name: {{ .Values.appGreen.fileserver }}
        persistentVolumeClaim:
          claimName: {{ .Values.appGreen.fileserver }}
      - configMap:
            defaultMode: 420
            name: {{ .Values.appGreen.configMap.name }}
        name: {{ .Values.appGreen.configMap.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    labels:
      app: php-fpm
    name: {{ .Values.appGreen.configMap.name }}
    namespace: {{ .Values.appGreen.namespace }}
data:
  www.conf: |
    [www]
    user=www-data
    group=www-data
    listen=127.0.0.1:9000
    pm.status_path=/status
    php_admin_value[display_errors] = Off
    php_admin_flag[log_errors] = on
    php_admin_value[error_log] = /var/log/fpm-php.www.log